spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/goosdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: goos
    password: goos

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
